In [1]:
import numpy as np

In [4]:
a = np.arange(60, dtype=np.int32).reshape((3,4,5))
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [7]:
np.random.shuffle(a)
print(a)

[[[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [ ]:
a = np.random.randint(0, 10, size=(20,2))
print(a)
temp = a[:,1]
temp[temp==1] = 0; 
print(a)
b, _ = np.unique(a, return_counts=True, axis=0)
print(b)

In [ ]:
a = [[1,2,3], [4,5,6]]
b = dict(zip(a[0], a[1]))
print(b)

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

In [ ]:
def swap_column(data_array, column_idx1, column_idx2):
            data_array[:, [column_idx1, column_idx2]] = data_array[:, [column_idx2, column_idx1]]

In [ ]:
swap_column(a, 1, 2)
print(a)

In [ ]:
a = np.random.randint(0,200, size=(10,10))
print(a.dtype)
a = a.astype(np.float32)
print(a.dtype)

In [ ]:
sort_idx = np.argsort(a, axis=0)
print(sort_idx[::-1])

In [ ]:
print(a[sort_idx[::-1]])

In [ ]:
a = [i for i in range(10)]
print(a)

In [ ]:
import csv

In [ ]:
raw_data_list= np.loadtxt('E:/DataSets/kddcup.data/kddcup.data.corrected', delimiter=',', dtype=np.string_)

In [ ]:
raw_data_list.dtype, raw_data_list.shape, raw_data_list.nbytes

In [8]:
import torch

In [9]:
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([1,3,3,4,5])

In [14]:
c = a == b
print(c)

tensor([ True, False,  True,  True,  True])


In [13]:
d = c.sum()
print(d)

tensor(4)
