In [3]:
import numpy as np
import torch

In [23]:
d = [2,3,4]
a = np.array([1,2,3,4,5,6,7,5,4,3,2,1])
b = a in d
print(b)
c = a[b]
print(c)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [4]:
a = np.arange(60, dtype=np.int32).reshape((3,4,5))
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [7]:
np.random.shuffle(a)
print(a)

[[[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [ ]:
a = np.random.randint(0, 10, size=(20,2))
print(a)
temp = a[:,1]
temp[temp==1] = 0; 
print(a)
b, _ = np.unique(a, return_counts=True, axis=0)
print(b)

In [ ]:
a = [[1,2,3], [4,5,6]]
b = dict(zip(a[0], a[1]))
print(b)

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

In [ ]:
def swap_column(data_array, column_idx1, column_idx2):
            data_array[:, [column_idx1, column_idx2]] = data_array[:, [column_idx2, column_idx1]]

In [ ]:
swap_column(a, 1, 2)
print(a)

In [ ]:
a = np.random.randint(0,200, size=(10,10))
print(a.dtype)
a = a.astype(np.float32)
print(a.dtype)

In [ ]:
sort_idx = np.argsort(a, axis=0)
print(sort_idx[::-1])

In [ ]:
print(a[sort_idx[::-1]])

In [ ]:
a = [i for i in range(10)]
print(a)

In [ ]:
import csv

In [ ]:
raw_data_list= np.loadtxt('E:/DataSets/kddcup.data/kddcup.data.corrected', delimiter=',', dtype=np.string_)

In [ ]:
raw_data_list.dtype, raw_data_list.shape, raw_data_list.nbytes

In [8]:
import torch

In [9]:
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([1,3,3,4,5])

In [14]:
c = a == b
print(c)

tensor([ True, False,  True,  True,  True])


In [13]:
d = c.sum()
print(d)

tensor(4)


In [7]:
a = {1:2, 2:4, 4:8}
b = a.keys()
print(b)

dict_keys([1, 2, 4])


In [8]:
for i in b:
    print(i)

1
2
4


In [3]:
a = [(1,), (3,), (5,)]
b = ()
for i in a:
    b = b + i
print(b)

(1, 3, 5)


In [1]:
a = 10
b = 2
c = a / b
print(c, type(c))

5.0 <class 'float'>


In [4]:
for i in range(3,2):
    print(i)

In [1]:
a = ' abcdefg'
b = a[1:]
print(b)

abcdefg


In [7]:
data = np.loadtxt('E:/DataSets/CIC-IDS2017/Wednesday-workingHours.pcap_ISCX.csv', dtype=np.string_, delimiter=',')

In [10]:
data_tmp = np.loadtxt('E:/DataSets/CIC-IDS2017/Monday-WorkingHours.pcap_ISCX.csv', dtype=np.string_, delimiter=',')
data = np.vstack((data, data_tmp))

MemoryError: cannot allocate memory for array

In [8]:
print(data.shape)

(692704, 79)
