In [1]:
import numpy as np
import torch

In [2]:
torch.rand()

TypeError: rand() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [23]:
d = [2,3,4]
a = np.array([1,2,3,4,5,6,7,5,4,3,2,1])
b = a in d
print(b)
c = a[b]
print(c)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [4]:
a = np.arange(60, dtype=np.int32).reshape((3,4,5))
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [7]:
np.random.shuffle(a)
print(a)

[[[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [ ]:
a = np.random.randint(0, 10, size=(20,2))
print(a)
temp = a[:,1]
temp[temp==1] = 0; 
print(a)
b, _ = np.unique(a, return_counts=True, axis=0)
print(b)

In [ ]:
a = [[1,2,3], [4,5,6]]
b = dict(zip(a[0], a[1]))
print(b)

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

In [ ]:
def swap_column(data_array, column_idx1, column_idx2):
            data_array[:, [column_idx1, column_idx2]] = data_array[:, [column_idx2, column_idx1]]

In [ ]:
swap_column(a, 1, 2)
print(a)

In [ ]:
a = np.random.randint(0,200, size=(10,10))
print(a.dtype)
a = a.astype(np.float32)
print(a.dtype)

In [ ]:
sort_idx = np.argsort(a, axis=0)
print(sort_idx[::-1])

In [ ]:
print(a[sort_idx[::-1]])

In [ ]:
a = [i for i in range(10)]
print(a)

In [ ]:
import csv

In [ ]:
raw_data_list= np.loadtxt('E:/DataSets/kddcup.data/kddcup.data.corrected', delimiter=',', dtype=np.string_)

In [ ]:
raw_data_list.dtype, raw_data_list.shape, raw_data_list.nbytes

In [8]:
import torch

In [9]:
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([1,3,3,4,5])

In [14]:
c = a == b
print(c)

tensor([ True, False,  True,  True,  True])


In [13]:
d = c.sum()
print(d)

tensor(4)


In [7]:
a = {1:2, 2:4, 4:8}
b = a.keys()
print(b)

dict_keys([1, 2, 4])


In [8]:
for i in b:
    print(i)

1
2
4


In [3]:
a = [(1,), (3,), (5,)]
b = ()
for i in a:
    b = b + i
print(b)

(1, 3, 5)


In [1]:
a = 10
b = 2
c = a / b
print(c, type(c))

5.0 <class 'float'>


In [4]:
for i in range(3,2):
    print(i)

In [1]:
a = ' abcdefg'
b = a[1:]
print(b)

abcdefg


In [7]:
data = np.loadtxt('E:/DataSets/CIC-IDS2017/Wednesday-workingHours.pcap_ISCX.csv', dtype=np.string_, delimiter=',')

In [10]:
data_tmp = np.loadtxt('E:/DataSets/CIC-IDS2017/Monday-WorkingHours.pcap_ISCX.csv', dtype=np.string_, delimiter=',')
data = np.vstack((data, data_tmp))

MemoryError: cannot allocate memory for array

In [8]:
print(data.shape)

(692704, 79)


In [2]:
a = np.array([])

In [3]:
b = np.array([2])

In [4]:
c = np.concatenate((a, b),axis=0)
print(c)

[2.]


In [3]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows',None)

In [ ]:
df = pd.read_csv('E:/DataSets/CIC-IDS2016/raw_data/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv', header=0, index_col=False)
print(df.iloc[:5], df.shape)
df = df.replace(np.inf, np.nan).replace(-np.inf, np.nan).replace('', np.nan).dropna()
print(df.iloc[:5], df.shape)
df.to_csv('E:/DataSets/CIC-IDS2016/cic_ids_2017_test_1.csv', header=False)

In [12]:
a = np.array([[5,6],[5,4],[5,6]])
b = pd.DataFrame(a)
print(b)

   0  1
0  5  6
1  5  4
2  5  6


In [13]:
columns = b.columns.to_list()
for i in columns:
    col_max = b[i].max()
    col_min = b[i].min()
    if col_max == col_min:
        b[i] = 0
    else:
        b[i] = (b[i] - col_min)/(col_max-col_min)
print(b)

   0    1
0  0  1.0
1  0  0.0
2  0  1.0


In [9]:
b.shape

(2, 2)

In [5]:
a = [1,2,3,4,5]
b = [2,3]
c = a[b]
print(c)

TypeError: list indices must be integers or slices, not list

In [31]:
a = [8.750025229239411e-07,0.00010725010725010725,0.0,3.9775165642630605e-05,0.0,0.002440068493150685,0.0,0.006396383398105218,0.00466828995507702,0.0,0.0,0.0,0.0,0.0034165401280693308,0.40576923077,4.453781475178307e-07,8.171752896226416e-07,8.499999929166668e-07,1.344537668243784e-07,8.666666666666667e-07,4.3333333333333335e-07,8.35904276960193e-07,8.416666666666666e-07,3.3333333055555556e-08,0.0,0.0,0.0,0.0,0.0,1.0,-1,0.0,-1,0.0001835802742995265,0.0,0.009615384616666667,0.0,0.0,0.002440068493150685,0.01647046232594684,0.006023431282105013,3.6261160714285715e-05,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.01952054794520548,0.006396383398105218,0.0,-1,-1,-1,-1,-1,-1,0.00010725010725010725,3.9775165642630605e-05,0.0,0.0,0.0049285888671875,0.0,5.437146585471944e-05,0.5714285714285714,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]

In [32]:
print(len(a))

94


In [2]:
columns_name = [
            ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets',
            ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
            ' Fwd Packet Length Std', 'Bwd Packet Length Max', ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
            ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
            ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total',
            ' Bwd IAT Mean', ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
            ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
            ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
            'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
            ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size', ' Avg Fwd Segment Size',
            ' Avg Bwd Segment Size', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
            ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes', ' Subflow Bwd Packets',
            ' Subflow Bwd Bytes', 'Init_Win_bytes_forward', ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
            ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
            ' Idle Max', ' Idle Min', ' Destination Port_0', ' Destination Port_21', ' Destination Port_22',
            ' Destination Port_53', ' Destination Port_80', ' Destination Port_443', ' Protocol_0', ' Protocol_6',
            ' Protocol_17', ' Label_BENIGN', ' Label_Bot', ' Label_Brute Force', ' Label_DDoS', ' Label_Dos',
            ' Label_Heartbleed', ' Label_Infiltration', ' Label_PortScan', ' Label_Web Attack'
        ]
print(len(columns_name))

94
